import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's repository.
*/
`;

const prod = process.argv[2] === "production";

// Two entry points: the plugin code (main.js) and its stylesheet
// (styles.css, which @imports the shared A3 page styles from @a3/core).
const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: [
        { in: "src/main.ts", out: "main" },
        { in: "src/styles.css", out: "styles" },
    ],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
        ...builtinModules.map((m) => `node:${m}`),
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    minify: prod,
    treeShaking: true,
    outdir: ".",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
